export const newRow = [
                {
                    rowTitle: '',
                    cols: 1,
                    stageColumns: [
                        {
                            id: 1,
                            style: {
                                width: '100%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '12',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va el título',
                                text: '<p>Aquí va el título</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                    ]
                },
                {
                    rowTitle: '',
                    cols: 2,
                    stageColumns: [
                        {
                            id: 1,
                            style: {
                                width: '50%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '6',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va el título',
                                text: '<p>Aquí va el título</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 2,
                            style: {
                                width: '50%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '6',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va el título',
                                text: '<p>Aquí va el título</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                    ]
                },
                {
                    rowTitle: '',
                    cols: 4,
                    stageColumns: [
                        {
                            id: 1,
                            style: {
                                width: '41.66%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '5',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va la descripción',
                                text: '<p>Aquí va la descripción</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 2,
                            style: {
                                width: '16.66%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'right',
                            },
                            col: '2',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'variable',
                                value: '{{variable_1}}',
                                text: '<p>{{variable_1}}</p>',
                                numeric: true,
                                allowDecimal: false,
                                decimalLimit: 0,
                                autocompletion: false,
                                autocompletionList: [],
                            },],
                        },
                        {
                            id: 3,
                            style: {
                                width: '8.33%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '1',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Unidades',
                                text: '<p>Unidades</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 4,
                            style: {
                                width: '33.35%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '4',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'VR',
                                text: '<p>VR</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        
                    ],
                },
                {
                    rowTitle: 'SOLO VR',
                    cols: 4,
                    stageColumns: [
                        {
                            id: 1,
                            style: {
                                width: '41.66%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '5',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: '',
                                text: '',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 2,
                            style: {
                                width: '16.66%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'right',
                            },
                            col: '2',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: '',
                                text: '',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 3,
                            style: {
                                width: '8.33%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '1',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: '',
                                text: '',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 4,
                            style: {
                                width: '33.35%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '4',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'VR',
                                text: '<p>VR</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        
                    ],
                },
                {
                    rowTitle: 'SOLO TEXTO',
                    cols: 4,
                    stageColumns: [
                        {
                            id: 1,
                            style: {
                                width: '25%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '3',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va la descripción',
                                text: '<p>Aquí va la descripción</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 2,
                            style: {
                                width: '25%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '3',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va la descripción',
                                text: '<p>Aquí va la descripción</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 3,
                            style: {
                                width: '25%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '3',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va la descripción',
                                text: '<p>Aquí va la descripción</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 4,
                            style: {
                                width: '25%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '3',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Aquí va la descripción',
                                text: '<p>Aquí va la descripción</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        
                    ],
                },
                {
                    rowTitle: '',
                    cols: 6,
                    stageColumns: [
                        {
                            id: 1,
                            style: {
                                width: '16.66%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '2',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Descripción',
                                text: '<p>Descripción</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 2,
                            style: {
                                width: '25.01%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '2',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'variable',
                                value: '{{variable_1}}',
                                text: '<p>{{variable_1}}</p>',
                                numeric: true,
                                allowDecimal: false,
                                decimalLimit: 0,
                                autocompletion: false,
                                autocompletionList: [],
                            },],
                        },
                        {
                            id: 3,
                            style: {
                                width: '8.33%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '1',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Uni',
                                text: '<p>Uni</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 4,
                            style: {
                                width: '16.66%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '2',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Descripción',
                                text: '<p>Descripción</p>',
                                numeric: false, 
                                isFormula: false, 
                                autocompletion: false, 
                                autocompletionList: []
                            },],
                        },
                        {
                            id: 5,
                            style: {
                                width: '25.01%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '2',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'variable',
                                value: '{{variable_2}}',
                                text: '<p>{{variable_2}}</p>',
                                numeric: true,
                                allowDecimal: false,
                                decimalLimit: 0,
                                autocompletion: false,
                                autocompletionList: [],
                            },],
                        },
                        {
                            id: 6,
                            style: {
                                width: '8.33%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'left',
                            },
                            col: '1',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Uni',
                                text: '<p>Uni</p>',
                                numeric: false,
                                isFormula: false,
                                autocompletion: false,
                                autocompletionList: []
                            },],
                        },
                        
                    ],
                },
                {
                    rowTitle: 'Módulo antibiograma',
                    cols: 1,
                    stageColumns: [
                        {
                            id: 1,
                            style: {
                                width: '100%',
                                backgroundColor: 'white',
                                border: '0 solid white',
                                paddingTop: '0',
                                paddingRight: '0',
                                paddingBottom: '0',
                                paddingLeft: '0',
                                textAlign: 'center',
                            },
                            col: '12',
                            activeColumn: false,
                            over: false,
                            content: [{
                                active: false,
                                type: 'label',
                                value: 'Módulo antibiograma',
                                text: '<p>Módulo antibiograma</p>',
                                numeric: false,
                                isFormula: false,
                                autocompletion: false,
                                autocompletionList: []
                            },],
                        },
                    ],
                    antibiograma: true
                },
            ];
